### ISSUE TITLE
update egg

### ISSUE THREAD

**Issue by mwillsey** [oflatt/egg-herbie#1]
It'd be nice to update the version of egg that herbie uses.

One obstacle to doing this is the current interface lets herbie do the driving, where new egg wants to take control with the new `Runner` interface.

I've prototyped a binary that takes in rules and expressions and simplifies them. Conceptually, herbie could call with binary with very little friction.
https://github.com/mwillsey/egg-herbie-new

**Comment by pavpanchekha** [comment]
This was closed by #5. There are still problems---data is not recorded correctly Herbie-side---but mostly things work.
